### ISSUE TITLE
Implement Integration Tests in Hardhat

### ISSUE THREAD

**Issue by samtvlabs** [tvl-labs/khalani-core#167]
## Description 

Implement integration tests using HH.

## Tasks / User Stories

- [ ] As an LP , I want to deposit Tokens to the A CCLP Pool, so that I can earn protocol fees for Liquidity Provisioning.
-  [ ] As an LP , I want to remove Tokens to the A CCLP Pool, so that I can reclaim my tokens
-  [ ] As an LP , I want to Add Tokens to the A CALP Pool, so that I can earn protocol fees for Liquidity Provisioning.
- [ ] As an LP , I want to remove USDC  to the A CALP Pool, so thatI can reclaim my tokens
- [ ] As  a USER, I want to bridge USDC from Sepolia to Avalanche.
