### ISSUE TITLE
Reserve Vaults 

### ISSUE THREAD

**Issue by samtvlabs** [tvl-labs/khalani-core#191]
## Description

The reserve vaults are a means for the protocol to invest idle assets in yield generating opportunities . For m2 , we cover implementing the vault from the protocol investing the entire amount. We will cover split this revenue to stakers in subsequent milestones

### User Stories 

- As a PROTOCOL , I want to be able to deposit excess liquidity from the chain's assets reserves into the Reserve Vaults , so that I can earn interest on idle funds. 
- As a PROTOCOL , I want to be able to withdraw assets from the Reserve Vaults, so that I can provide exit Liquidity

### Acceptance Criteria

- Given that the PROTOCOL deposits funds into the Reserve Vault , It should:
     -   reduce the Asset Reserve by the proportional amount
     -  reduce mint a vault share to the protocol.
- Given that the PROTOCOL withdraws funds from the Reserve Vault
    - Increase the Asset Reserve by the proportional amount
    - Burn the proportional amount of the vault share. 

## Tasks

- [x] #192 + Fault Factory 3 / 4 days
- [x] #193  1 week for Vault
- [x] #194 1 week for strategy  
- [x] #197

## Related Issues

- [Reserve Vaults and Staking Technical Spec ](https://github.com/orgs/tvl-labs/discussions/74)
