### ISSUE TITLE
Develop Vault

### ISSUE THREAD

**Issue by samtvlabs** [tvl-labs/khalani-core#193]
## Description

The vault is responsible for holding user funds and disbursing / redeeming them from different strategies.  It also has functions to manage the collateral of the system , ensuring that there is enough exit liquidity in the Asset reserves.

## Tasks

- [ ] Implement Deposit / Mint
- [ ] Implement Redeem / Burn
- [ ] Implement Strategy Management
