### ISSUE TITLE
Gas MVP

### ISSUE THREAD

**Issue by samtvlabs** [tvl-labs/khalani-core#196]
## Description

This covers the initial solution for interchain gas payments 

## Tasks

- [x] Make the entry-points `payable` functions and transfer the payment to the registered `InterchainGasPaymaster`
- [x] Encode the received gas payment to the message payload and dispatch to Khalani chain
- [x] Deploy a `KhalaniInterchainGasPaymaster` contract and register it in the Khalani's facet
- [x] on receiving the message, decode the gas payment payload and forward it to the `KhalaniInterchainGasPaymaster` 
- [x] script to deploy StorageGasOracle for Khalani and Godwoken
- [x] script to deploy our own InterchainGasPaymaster
- [x] deploy gas oracles and IGPs to all end chains
- [ ] deploy the new protocol instance with our IGPs registered

## Related Issues

- [Gas MVP](https://github.com/orgs/tvl-labs/discussions/34#discussioncomment-6283095) 
- https://github.com/tvl-labs/infrastructure/issues/283
- https://github.com/tvl-labs/khalani-sdk/issues/81
