### ISSUE TITLE
Cardano USDC

### ISSUE THREAD

**Issue by samtvlabs** [tvl-labs/khalani-core#205]
## Description

This task is for implementing Cardano mint / burn , as described in option 1 of this [discussion](https://github.com/orgs/tvl-labs/discussions/80).

## Acceptance Criteria 
- Bridge USDC token from Fuji and mint Cardano USDC.
- Bridge (burn) Cardano USDC and bridge to Fuji.

## Tasks 

- [x] https://github.com/tvl-labs/khalani-core/issues/203
- [x] https://github.com/tvl-labs/khalani-core/issues/202
- [x] https://github.com/tvl-labs/khalani-core/issues/201
- [x] https://github.com/tvl-labs/khalani-core/issues/204
- [x] #208
- [x] #209
- [x] #211
